# Generated by Django 5.0 on 2024-02-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_register_cpassword_alter_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cpassword',
        ),
    ]
