# Generated by Django 5.0 on 2024-02-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_register_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='uname',
            field=models.CharField(default='xyz', max_length=15),
        ),
    ]
